### ISSUE TITLE
Black windows when the effect is on

### ISSUE THREAD

**Issue by dmaliog** [a-parhom/LightlyShaders#128]
Black windows when the effect is on

VIDEO:
https://www.veed.io/view/acb82178-d793-4160-828e-f5b2718da55c?panel=share

INFO:

- Wayland
- Ver. KDE: 6.0.2
- Ver. KDE Fraemworks: 6.0.0
- Ver. QT: 6.6.2
- Ver. Kernel: 6.8.1-arch1-1 (64-бита)

```
➜  ~ git:(master) ✗ inxi -G
Graphics:
  Device-1: NVIDIA GP102 [GeForce GTX 1080 Ti] driver: nvidia v: 535.161.07
  Display: wayland server: X.Org v: 23.2.4 with: Xwayland v: 23.2.4
    compositor: kwin_wayland driver: X: loaded: nvidia
    gpu: nvidia,nvidia-nvswitch resolution: 2560x1440~165Hz
  API: EGL Message: No EGL data available.
  API: OpenGL v: 4.6.0 vendor: nvidia v: 535.161.07 renderer: NVIDIA
    GeForce GTX 1080 Ti/PCIe/SSE2
  API: Vulkan v: 1.3.279 drivers: nvidia surfaces: xcb,xlib,wayland
```
